obj-$(CONFIG_HUAWEI_CHARGER_AP) += charger_ap/
obj-$(CONFIG_CHARGER_PROTOCOL) += charger_protocol/

ccflags-y  += -I$(srctree)/drivers/huawei_platform/inputhub/$(TARGET_BOARD_PLATFORM)/

obj-y += huawei_charger_common.o
obj-y += huawei_charger_power_interface.o
