#
# Makefile for the linux kernel cgroup feature.
#

obj-$(CONFIG_HW_CGROUP_PIDS) += cgroup_pids.o
obj-$(CONFIG_CGROUP_IOLIMIT) += cgroup_io_limit.o
obj-$(CONFIG_HW_CGROUP_WORKINGSET) += cgroup_workingset.o
obj-$(CONFIG_DETECT_HUAWEI_HUNG_TASK) += huawei_hung_task.o huawei_init_watchdog.o
