obj-$(CONFIG_SCHARGER_V200)	    += schargerV200/
obj-$(CONFIG_SCHARGER_V300)	    += schargerV300/
obj-$(CONFIG_HI6523_CHARGER_SENSORHUB)           += schargerV300_sh/
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver/libhwsecurec/
