EXTRA_CFLAGS += -Idrivers/hisi/tzdriver/libhwsecurec/

obj-$(CONFIG_HISI_BATTERY_DATA)		+= hisi_battery_data.o
obj-$(CONFIG_HISI_BCI_BATTERY)		+= hisi_bci_battery.o
obj-$(CONFIG_HISI_COUL)		        += coul/
obj-$(CONFIG_HISI_CHARGER)		+= charger/
obj-$(CONFIG_HISI_SOH)	                += soh/
obj-$(CONFIG_HISI_ASW)	                += asw/
